class AudioRecording(db.Model):
  id = …
  user_id = …
  filename = …
  transcript = …
  file_hash = …
  created_at = …

class PracticeLog(db.Model):
  id = …
  user_id = …
  recording_id = …
  wer = …
  practiced_at = …

class Material(db.Model):
  id = …
  user_id = …
  material_name = …
  object_storage_key = …
  transcript = …
  upload_timestamp = …
