"""Add billing models and user enhancements

Revision ID: c01c719f0e47
Revises: 0bf396bece10
Create Date: 2025-05-09 15:37:40.153101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01c719f0e47'
down_revision = '0bf396bece10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('api_call_limit', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id'),
    sa.UniqueConstraint('stripe_product_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replit_user_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('current_subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_calls_monthly_limit', sa.Integer(), nullable=True),
    sa.Column('api_calls_monthly_used', sa.Integer(), nullable=True),
    sa.Column('api_calls_reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onetime_access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_calls_onetime_limit', sa.Integer(), nullable=True),
    sa.Column('api_calls_onetime_used', sa.Integer(), nullable=True),
    sa.Column('is_trial_period_active', sa.Boolean(), nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_api_call_limit', sa.Integer(), nullable=True),
    sa.Column('trial_api_call_used', sa.Integer(), nullable=True),
    sa.Column('is_special_free_account', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_current_subscription_id'), ['current_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_replit_user_id'), ['replit_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_replit_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_current_subscription_id'))

    op.drop_table('users')
    op.drop_table('subscription_products')
    # ### end Alembic commands ###
